### ISSUE TITLE
增加https://w.linovelib.com/支持

### ISSUE THREAD

**Issue by Darkari** [fangxx3863/biliNovel2Epub#2]
我试了试发现会报这个错
```
java.lang.NullPointerException: Cannot invoke "org.jsoup.nodes.Element.text()" because the return value of "org.jsoup.nodes.Document.selectFirst(String)" is null
        at cn.montaro.linovelib.core.fetcher.Fetcher.fetchNovel(Fetcher.java:39)
        at cn.montaro.linovelib.cli.Main.start(Main.java:59)
        at cn.montaro.linovelib.cli.Main.main(Main.java:34)
```
 https://www.linovelib.com 这个网址不知道为什么我上不去显示Access denied
不知道可不可以增加对https://w.linovelib.com  的支持，这个我能够上得去

**Comment by fangxx3863** [comment]
代码中就是使用的 https://w.linovelib.com 进不去有可能是你的网络问题
